import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Thomas Haudiquer - Front-end Developer</title>
        <meta name="Thomas Haudiquer - Front-end Developer" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

      </main>
      <footer>
        
      </footer>
    </div>
  )
}
